# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: c3zmxkvmd-capi-aws
  namespace: c3zmxkvmd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: c3zmxkvmd-capi-aws
subjects:
- kind: ServiceAccount
  name: c3zmxkvmd-capi-aws
